package com.inmobiliaria.model;
// Generated 4/03/2015 09:08:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name="ciudad"
    ,catalog="inmobiliaria"
)
public class Ciudad  implements java.io.Serializable {


     private Integer consecutivoCiudad;
     private Departamento departamento;
     private int idCiudad;
     private String nombreCiudad;
     private Set informacionPrincipals = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Ciudad() {
    }

	
    public Ciudad(Departamento departamento, int idCiudad, String nombreCiudad) {
        this.departamento = departamento;
        this.idCiudad = idCiudad;
        this.nombreCiudad = nombreCiudad;
    }
    public Ciudad(Departamento departamento, int idCiudad, String nombreCiudad, Set informacionPrincipals, Set usuarios) {
       this.departamento = departamento;
       this.idCiudad = idCiudad;
       this.nombreCiudad = nombreCiudad;
       this.informacionPrincipals = informacionPrincipals;
       this.usuarios = usuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="consecutivo_ciudad", unique=true, nullable=false)
    public Integer getConsecutivoCiudad() {
        return this.consecutivoCiudad;
    }
    
    public void setConsecutivoCiudad(Integer consecutivoCiudad) {
        this.consecutivoCiudad = consecutivoCiudad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="departamento_id_departamento", nullable=false)
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="id_ciudad", nullable=false)
    public int getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }

    
    @Column(name="nombre_ciudad", nullable=false, length=45)
    public String getNombreCiudad() {
        return this.nombreCiudad;
    }
    
    public void setNombreCiudad(String nombreCiudad) {
        this.nombreCiudad = nombreCiudad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ciudad")
    public Set getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ciudad")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


