package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private Integer consecutivoCiudad;
     private Departamento departamento;
     private int idCiudad;
     private String nombreCiudad;
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Ciudad() {
    }

	
    public Ciudad(Departamento departamento, int idCiudad, String nombreCiudad) {
        this.departamento = departamento;
        this.idCiudad = idCiudad;
        this.nombreCiudad = nombreCiudad;
    }
    public Ciudad(Departamento departamento, int idCiudad, String nombreCiudad, Set<InformacionPrincipal> informacionPrincipals, Set<Usuario> usuarios) {
       this.departamento = departamento;
       this.idCiudad = idCiudad;
       this.nombreCiudad = nombreCiudad;
       this.informacionPrincipals = informacionPrincipals;
       this.usuarios = usuarios;
    }
   
    public Integer getConsecutivoCiudad() {
        return this.consecutivoCiudad;
    }
    
    public void setConsecutivoCiudad(Integer consecutivoCiudad) {
        this.consecutivoCiudad = consecutivoCiudad;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public int getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }
    public String getNombreCiudad() {
        return this.nombreCiudad;
    }
    
    public void setNombreCiudad(String nombreCiudad) {
        this.nombreCiudad = nombreCiudad;
    }
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


