package com.inmobiliaria.model;
// Generated 4/03/2015 09:08:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cocina generated by hbm2java
 */
@Entity
@Table(name="cocina"
    ,catalog="inmobiliaria"
)
public class Cocina  implements java.io.Serializable {


     private Integer idCocina;
     private String nombreCocina;
     private Set informacionPrincipals = new HashSet(0);

    public Cocina() {
    }

	
    public Cocina(String nombreCocina) {
        this.nombreCocina = nombreCocina;
    }
    public Cocina(String nombreCocina, Set informacionPrincipals) {
       this.nombreCocina = nombreCocina;
       this.informacionPrincipals = informacionPrincipals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cocina", unique=true, nullable=false)
    public Integer getIdCocina() {
        return this.idCocina;
    }
    
    public void setIdCocina(Integer idCocina) {
        this.idCocina = idCocina;
    }

    
    @Column(name="nombre_cocina", nullable=false, length=45)
    public String getNombreCocina() {
        return this.nombreCocina;
    }
    
    public void setNombreCocina(String nombreCocina) {
        this.nombreCocina = nombreCocina;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cocina")
    public Set getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


