package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Condicion generated by hbm2java
 */
public class Condicion  implements java.io.Serializable {


     private Integer idCondicion;
     private String nombreCondicion;
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public Condicion() {
    }

	
    public Condicion(String nombreCondicion) {
        this.nombreCondicion = nombreCondicion;
    }
    public Condicion(String nombreCondicion, Set<InformacionPrincipal> informacionPrincipals) {
       this.nombreCondicion = nombreCondicion;
       this.informacionPrincipals = informacionPrincipals;
    }
   
    public Integer getIdCondicion() {
        return this.idCondicion;
    }
    
    public void setIdCondicion(Integer idCondicion) {
        this.idCondicion = idCondicion;
    }
    public String getNombreCondicion() {
        return this.nombreCondicion;
    }
    
    public void setNombreCondicion(String nombreCondicion) {
        this.nombreCondicion = nombreCondicion;
    }
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


