package com.inmobiliaria.model;
// Generated 4/03/2015 09:08:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Condicion generated by hbm2java
 */
@Entity
@Table(name="condicion"
    ,catalog="inmobiliaria"
)
public class Condicion  implements java.io.Serializable {


     private Integer idCondicion;
     private String nombreCondicion;
     private Set informacionPrincipals = new HashSet(0);

    public Condicion() {
    }

	
    public Condicion(String nombreCondicion) {
        this.nombreCondicion = nombreCondicion;
    }
    public Condicion(String nombreCondicion, Set informacionPrincipals) {
       this.nombreCondicion = nombreCondicion;
       this.informacionPrincipals = informacionPrincipals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_condicion", unique=true, nullable=false)
    public Integer getIdCondicion() {
        return this.idCondicion;
    }
    
    public void setIdCondicion(Integer idCondicion) {
        this.idCondicion = idCondicion;
    }

    
    @Column(name="nombre_condicion", nullable=false, length=10)
    public String getNombreCondicion() {
        return this.nombreCondicion;
    }
    
    public void setNombreCondicion(String nombreCondicion) {
        this.nombreCondicion = nombreCondicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="condicion")
    public Set getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


