package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int idDepartamento;
     private Pais pais;
     private String nombreDepartamento;
     private Set<Ciudad> ciudads = new HashSet<Ciudad>(0);
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Departamento() {
    }

	
    public Departamento(int idDepartamento, Pais pais, String nombreDepartamento) {
        this.idDepartamento = idDepartamento;
        this.pais = pais;
        this.nombreDepartamento = nombreDepartamento;
    }
    public Departamento(int idDepartamento, Pais pais, String nombreDepartamento, Set<Ciudad> ciudads, Set<InformacionPrincipal> informacionPrincipals, Set<Usuario> usuarios) {
       this.idDepartamento = idDepartamento;
       this.pais = pais;
       this.nombreDepartamento = nombreDepartamento;
       this.ciudads = ciudads;
       this.informacionPrincipals = informacionPrincipals;
       this.usuarios = usuarios;
    }
   
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public Set<Ciudad> getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set<Ciudad> ciudads) {
        this.ciudads = ciudads;
    }
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


