package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EspecificacionesVarias generated by hbm2java
 */
public class EspecificacionesVarias  implements java.io.Serializable {


     private Integer idEspecificacionesVarias;
     private String nombreEspecificiacionesVarias;
     private Set<InformacionPrincipalHasEspecificacionesVarias> informacionPrincipalHasEspecificacionesVariases = new HashSet<InformacionPrincipalHasEspecificacionesVarias>(0);

    public EspecificacionesVarias() {
    }

	
    public EspecificacionesVarias(String nombreEspecificiacionesVarias) {
        this.nombreEspecificiacionesVarias = nombreEspecificiacionesVarias;
    }
    public EspecificacionesVarias(String nombreEspecificiacionesVarias, Set<InformacionPrincipalHasEspecificacionesVarias> informacionPrincipalHasEspecificacionesVariases) {
       this.nombreEspecificiacionesVarias = nombreEspecificiacionesVarias;
       this.informacionPrincipalHasEspecificacionesVariases = informacionPrincipalHasEspecificacionesVariases;
    }
   
    public Integer getIdEspecificacionesVarias() {
        return this.idEspecificacionesVarias;
    }
    
    public void setIdEspecificacionesVarias(Integer idEspecificacionesVarias) {
        this.idEspecificacionesVarias = idEspecificacionesVarias;
    }
    public String getNombreEspecificiacionesVarias() {
        return this.nombreEspecificiacionesVarias;
    }
    
    public void setNombreEspecificiacionesVarias(String nombreEspecificiacionesVarias) {
        this.nombreEspecificiacionesVarias = nombreEspecificiacionesVarias;
    }
    public Set<InformacionPrincipalHasEspecificacionesVarias> getInformacionPrincipalHasEspecificacionesVariases() {
        return this.informacionPrincipalHasEspecificacionesVariases;
    }
    
    public void setInformacionPrincipalHasEspecificacionesVariases(Set<InformacionPrincipalHasEspecificacionesVarias> informacionPrincipalHasEspecificacionesVariases) {
        this.informacionPrincipalHasEspecificacionesVariases = informacionPrincipalHasEspecificacionesVariases;
    }




}


