package com.inmobiliaria.model;
// Generated 4/03/2015 09:08:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estrato generated by hbm2java
 */
@Entity
@Table(name="estrato"
    ,catalog="inmobiliaria"
)
public class Estrato  implements java.io.Serializable {


     private Integer idEstrato;
     private int estratoSocial;
     private Set informacionPrincipals = new HashSet(0);

    public Estrato() {
    }

	
    public Estrato(int estratoSocial) {
        this.estratoSocial = estratoSocial;
    }
    public Estrato(int estratoSocial, Set informacionPrincipals) {
       this.estratoSocial = estratoSocial;
       this.informacionPrincipals = informacionPrincipals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_estrato", unique=true, nullable=false)
    public Integer getIdEstrato() {
        return this.idEstrato;
    }
    
    public void setIdEstrato(Integer idEstrato) {
        this.idEstrato = idEstrato;
    }

    
    @Column(name="estrato_social", nullable=false)
    public int getEstratoSocial() {
        return this.estratoSocial;
    }
    
    public void setEstratoSocial(int estratoSocial) {
        this.estratoSocial = estratoSocial;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estrato")
    public Set getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


