package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estrato generated by hbm2java
 */
public class Estrato  implements java.io.Serializable {


     private Integer idEstrato;
     private int estratoSocial;
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public Estrato() {
    }

	
    public Estrato(int estratoSocial) {
        this.estratoSocial = estratoSocial;
    }
    public Estrato(int estratoSocial, Set<InformacionPrincipal> informacionPrincipals) {
       this.estratoSocial = estratoSocial;
       this.informacionPrincipals = informacionPrincipals;
    }
   
    public Integer getIdEstrato() {
        return this.idEstrato;
    }
    
    public void setIdEstrato(Integer idEstrato) {
        this.idEstrato = idEstrato;
    }
    public int getEstratoSocial() {
        return this.estratoSocial;
    }
    
    public void setEstratoSocial(int estratoSocial) {
        this.estratoSocial = estratoSocial;
    }
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


