package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Garaje generated by hbm2java
 */
public class Garaje  implements java.io.Serializable {


     private Integer idGaraje;
     private String cantidadGaraje;
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public Garaje() {
    }

	
    public Garaje(String cantidadGaraje) {
        this.cantidadGaraje = cantidadGaraje;
    }
    public Garaje(String cantidadGaraje, Set<InformacionPrincipal> informacionPrincipals) {
       this.cantidadGaraje = cantidadGaraje;
       this.informacionPrincipals = informacionPrincipals;
    }
   
    public Integer getIdGaraje() {
        return this.idGaraje;
    }
    
    public void setIdGaraje(Integer idGaraje) {
        this.idGaraje = idGaraje;
    }
    public String getCantidadGaraje() {
        return this.cantidadGaraje;
    }
    
    public void setCantidadGaraje(String cantidadGaraje) {
        this.cantidadGaraje = cantidadGaraje;
    }
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


