package com.inmobiliaria.model;
// Generated 4/03/2015 09:08:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Garaje generated by hbm2java
 */
@Entity
@Table(name="garaje"
    ,catalog="inmobiliaria"
)
public class Garaje  implements java.io.Serializable {


     private Integer idGaraje;
     private String cantidadGaraje;
     private Set informacionPrincipals = new HashSet(0);

    public Garaje() {
    }

	
    public Garaje(String cantidadGaraje) {
        this.cantidadGaraje = cantidadGaraje;
    }
    public Garaje(String cantidadGaraje, Set informacionPrincipals) {
       this.cantidadGaraje = cantidadGaraje;
       this.informacionPrincipals = informacionPrincipals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_garaje", unique=true, nullable=false)
    public Integer getIdGaraje() {
        return this.idGaraje;
    }
    
    public void setIdGaraje(Integer idGaraje) {
        this.idGaraje = idGaraje;
    }

    
    @Column(name="cantidad_garaje", nullable=false, length=10)
    public String getCantidadGaraje() {
        return this.cantidadGaraje;
    }
    
    public void setCantidadGaraje(String cantidadGaraje) {
        this.cantidadGaraje = cantidadGaraje;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="garaje")
    public Set getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


