package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Genero generated by hbm2java
 */
public class Genero  implements java.io.Serializable {


     private Integer idGenero;
     private String nombreGenero;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Genero() {
    }

	
    public Genero(String nombreGenero) {
        this.nombreGenero = nombreGenero;
    }
    public Genero(String nombreGenero, Set<Usuario> usuarios) {
       this.nombreGenero = nombreGenero;
       this.usuarios = usuarios;
    }
   
    public Integer getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(Integer idGenero) {
        this.idGenero = idGenero;
    }
    public String getNombreGenero() {
        return this.nombreGenero;
    }
    
    public void setNombreGenero(String nombreGenero) {
        this.nombreGenero = nombreGenero;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


