package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1



/**
 * IdentificacionInmobiliaria generated by hbm2java
 */
public class IdentificacionInmobiliaria  implements java.io.Serializable {


     private Integer idIdentificacionInmobiliaria;
     private String nombreInmobiliaria;

    public IdentificacionInmobiliaria() {
    }

    public IdentificacionInmobiliaria(String nombreInmobiliaria) {
       this.nombreInmobiliaria = nombreInmobiliaria;
    }
   
    public Integer getIdIdentificacionInmobiliaria() {
        return this.idIdentificacionInmobiliaria;
    }
    
    public void setIdIdentificacionInmobiliaria(Integer idIdentificacionInmobiliaria) {
        this.idIdentificacionInmobiliaria = idIdentificacionInmobiliaria;
    }
    public String getNombreInmobiliaria() {
        return this.nombreInmobiliaria;
    }
    
    public void setNombreInmobiliaria(String nombreInmobiliaria) {
        this.nombreInmobiliaria = nombreInmobiliaria;
    }




}


