package com.inmobiliaria.model;
// Generated 4/03/2015 09:08:20 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IdentificacionInmobiliaria generated by hbm2java
 */
@Entity
@Table(name="identificacion_inmobiliaria"
    ,catalog="inmobiliaria"
)
public class IdentificacionInmobiliaria  implements java.io.Serializable {


     private Integer idIdentificacionInmobiliaria;
     private String nombreInmobiliaria;

    public IdentificacionInmobiliaria() {
    }

    public IdentificacionInmobiliaria(String nombreInmobiliaria) {
       this.nombreInmobiliaria = nombreInmobiliaria;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_identificacion_inmobiliaria", unique=true, nullable=false)
    public Integer getIdIdentificacionInmobiliaria() {
        return this.idIdentificacionInmobiliaria;
    }
    
    public void setIdIdentificacionInmobiliaria(Integer idIdentificacionInmobiliaria) {
        this.idIdentificacionInmobiliaria = idIdentificacionInmobiliaria;
    }

    
    @Column(name="nombre_inmobiliaria", nullable=false, length=45)
    public String getNombreInmobiliaria() {
        return this.nombreInmobiliaria;
    }
    
    public void setNombreInmobiliaria(String nombreInmobiliaria) {
        this.nombreInmobiliaria = nombreInmobiliaria;
    }




}


