package com.inmobiliaria.model;
// Generated 4/03/2015 09:08:20 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InformacionPrincipalHasEspecificacionesVariasId generated by hbm2java
 */
@Embeddable
public class InformacionPrincipalHasEspecificacionesVariasId  implements java.io.Serializable {


     private int informacionPrincipalIdInformacionPrincipal;
     private int especificacionesVariasIdEspecificacionesVarias;

    public InformacionPrincipalHasEspecificacionesVariasId() {
    }

    public InformacionPrincipalHasEspecificacionesVariasId(int informacionPrincipalIdInformacionPrincipal, int especificacionesVariasIdEspecificacionesVarias) {
       this.informacionPrincipalIdInformacionPrincipal = informacionPrincipalIdInformacionPrincipal;
       this.especificacionesVariasIdEspecificacionesVarias = especificacionesVariasIdEspecificacionesVarias;
    }
   


    @Column(name="informacion_principal_id_informacion_principal", nullable=false)
    public int getInformacionPrincipalIdInformacionPrincipal() {
        return this.informacionPrincipalIdInformacionPrincipal;
    }
    
    public void setInformacionPrincipalIdInformacionPrincipal(int informacionPrincipalIdInformacionPrincipal) {
        this.informacionPrincipalIdInformacionPrincipal = informacionPrincipalIdInformacionPrincipal;
    }


    @Column(name="especificaciones_varias_id_especificaciones_varias", nullable=false)
    public int getEspecificacionesVariasIdEspecificacionesVarias() {
        return this.especificacionesVariasIdEspecificacionesVarias;
    }
    
    public void setEspecificacionesVariasIdEspecificacionesVarias(int especificacionesVariasIdEspecificacionesVarias) {
        this.especificacionesVariasIdEspecificacionesVarias = especificacionesVariasIdEspecificacionesVarias;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InformacionPrincipalHasEspecificacionesVariasId) ) return false;
		 InformacionPrincipalHasEspecificacionesVariasId castOther = ( InformacionPrincipalHasEspecificacionesVariasId ) other; 
         
		 return (this.getInformacionPrincipalIdInformacionPrincipal()==castOther.getInformacionPrincipalIdInformacionPrincipal())
 && (this.getEspecificacionesVariasIdEspecificacionesVarias()==castOther.getEspecificacionesVariasIdEspecificacionesVarias());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getInformacionPrincipalIdInformacionPrincipal();
         result = 37 * result + this.getEspecificacionesVariasIdEspecificacionesVarias();
         return result;
   }   


}


