package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * NumeroPlantas generated by hbm2java
 */
public class NumeroPlantas  implements java.io.Serializable {


     private Integer idNumeroPlantas;
     private String cantidadPlantas;
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public NumeroPlantas() {
    }

	
    public NumeroPlantas(String cantidadPlantas) {
        this.cantidadPlantas = cantidadPlantas;
    }
    public NumeroPlantas(String cantidadPlantas, Set<InformacionPrincipal> informacionPrincipals) {
       this.cantidadPlantas = cantidadPlantas;
       this.informacionPrincipals = informacionPrincipals;
    }
   
    public Integer getIdNumeroPlantas() {
        return this.idNumeroPlantas;
    }
    
    public void setIdNumeroPlantas(Integer idNumeroPlantas) {
        this.idNumeroPlantas = idNumeroPlantas;
    }
    public String getCantidadPlantas() {
        return this.cantidadPlantas;
    }
    
    public void setCantidadPlantas(String cantidadPlantas) {
        this.cantidadPlantas = cantidadPlantas;
    }
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


