package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * NumeroAlcobas generated by hbm2java
 */
public class NumeroAlcobas  implements java.io.Serializable {


     private Integer idNumeroAlcobas;
     private String cantidadAlcobas;
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public NumeroAlcobas() {
    }

	
    public NumeroAlcobas(String cantidadAlcobas) {
        this.cantidadAlcobas = cantidadAlcobas;
    }
    public NumeroAlcobas(String cantidadAlcobas, Set<InformacionPrincipal> informacionPrincipals) {
       this.cantidadAlcobas = cantidadAlcobas;
       this.informacionPrincipals = informacionPrincipals;
    }
   
    public Integer getIdNumeroAlcobas() {
        return this.idNumeroAlcobas;
    }
    
    public void setIdNumeroAlcobas(Integer idNumeroAlcobas) {
        this.idNumeroAlcobas = idNumeroAlcobas;
    }
    public String getCantidadAlcobas() {
        return this.cantidadAlcobas;
    }
    
    public void setCantidadAlcobas(String cantidadAlcobas) {
        this.cantidadAlcobas = cantidadAlcobas;
    }
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


