package com.inmobiliaria.model;
// Generated 4/03/2015 09:08:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Opcion generated by hbm2java
 */
@Entity
@Table(name="opcion"
    ,catalog="inmobiliaria"
)
public class Opcion  implements java.io.Serializable {


     private Integer idOpcion;
     private String nombreOpcion;
     private Set informacionPrincipalHasEspecificacionesVariases = new HashSet(0);

    public Opcion() {
    }

	
    public Opcion(String nombreOpcion) {
        this.nombreOpcion = nombreOpcion;
    }
    public Opcion(String nombreOpcion, Set informacionPrincipalHasEspecificacionesVariases) {
       this.nombreOpcion = nombreOpcion;
       this.informacionPrincipalHasEspecificacionesVariases = informacionPrincipalHasEspecificacionesVariases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_opcion", unique=true, nullable=false)
    public Integer getIdOpcion() {
        return this.idOpcion;
    }
    
    public void setIdOpcion(Integer idOpcion) {
        this.idOpcion = idOpcion;
    }

    
    @Column(name="nombre_opcion", nullable=false, length=2)
    public String getNombreOpcion() {
        return this.nombreOpcion;
    }
    
    public void setNombreOpcion(String nombreOpcion) {
        this.nombreOpcion = nombreOpcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="opcion")
    public Set getInformacionPrincipalHasEspecificacionesVariases() {
        return this.informacionPrincipalHasEspecificacionesVariases;
    }
    
    public void setInformacionPrincipalHasEspecificacionesVariases(Set informacionPrincipalHasEspecificacionesVariases) {
        this.informacionPrincipalHasEspecificacionesVariases = informacionPrincipalHasEspecificacionesVariases;
    }




}


