package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Opcion generated by hbm2java
 */
public class Opcion  implements java.io.Serializable {


     private Integer idOpcion;
     private String nombreOpcion;
     private Set<InformacionPrincipalHasEspecificacionesVarias> informacionPrincipalHasEspecificacionesVariases = new HashSet<InformacionPrincipalHasEspecificacionesVarias>(0);

    public Opcion() {
    }

	
    public Opcion(String nombreOpcion) {
        this.nombreOpcion = nombreOpcion;
    }
    public Opcion(String nombreOpcion, Set<InformacionPrincipalHasEspecificacionesVarias> informacionPrincipalHasEspecificacionesVariases) {
       this.nombreOpcion = nombreOpcion;
       this.informacionPrincipalHasEspecificacionesVariases = informacionPrincipalHasEspecificacionesVariases;
    }
   
    public Integer getIdOpcion() {
        return this.idOpcion;
    }
    
    public void setIdOpcion(Integer idOpcion) {
        this.idOpcion = idOpcion;
    }
    public String getNombreOpcion() {
        return this.nombreOpcion;
    }
    
    public void setNombreOpcion(String nombreOpcion) {
        this.nombreOpcion = nombreOpcion;
    }
    public Set<InformacionPrincipalHasEspecificacionesVarias> getInformacionPrincipalHasEspecificacionesVariases() {
        return this.informacionPrincipalHasEspecificacionesVariases;
    }
    
    public void setInformacionPrincipalHasEspecificacionesVariases(Set<InformacionPrincipalHasEspecificacionesVarias> informacionPrincipalHasEspecificacionesVariases) {
        this.informacionPrincipalHasEspecificacionesVariases = informacionPrincipalHasEspecificacionesVariases;
    }




}


