package com.inmobiliaria.model;
// Generated 4/03/2015 09:08:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name="pais"
    ,catalog="inmobiliaria"
)
public class Pais  implements java.io.Serializable {


     private String siglasPais;
     private String nombrePais;
     private Set departamentos = new HashSet(0);

    public Pais() {
    }

	
    public Pais(String siglasPais, String nombrePais) {
        this.siglasPais = siglasPais;
        this.nombrePais = nombrePais;
    }
    public Pais(String siglasPais, String nombrePais, Set departamentos) {
       this.siglasPais = siglasPais;
       this.nombrePais = nombrePais;
       this.departamentos = departamentos;
    }
   
     @Id 

    
    @Column(name="siglas_pais", unique=true, nullable=false, length=45)
    public String getSiglasPais() {
        return this.siglasPais;
    }
    
    public void setSiglasPais(String siglasPais) {
        this.siglasPais = siglasPais;
    }

    
    @Column(name="nombre_pais", nullable=false, length=45)
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pais")
    public Set getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set departamentos) {
        this.departamentos = departamentos;
    }




}


