package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private String siglasPais;
     private String nombrePais;
     private Set<Departamento> departamentos = new HashSet<Departamento>(0);

    public Pais() {
    }

	
    public Pais(String siglasPais, String nombrePais) {
        this.siglasPais = siglasPais;
        this.nombrePais = nombrePais;
    }
    public Pais(String siglasPais, String nombrePais, Set<Departamento> departamentos) {
       this.siglasPais = siglasPais;
       this.nombrePais = nombrePais;
       this.departamentos = departamentos;
    }
   
    public String getSiglasPais() {
        return this.siglasPais;
    }
    
    public void setSiglasPais(String siglasPais) {
        this.siglasPais = siglasPais;
    }
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }
    public Set<Departamento> getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set<Departamento> departamentos) {
        this.departamentos = departamentos;
    }




}


