package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Parqueadero generated by hbm2java
 */
public class Parqueadero  implements java.io.Serializable {


     private Integer idParqueadero;
     private String cantidadParqueaderos;
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public Parqueadero() {
    }

	
    public Parqueadero(String cantidadParqueaderos) {
        this.cantidadParqueaderos = cantidadParqueaderos;
    }
    public Parqueadero(String cantidadParqueaderos, Set<InformacionPrincipal> informacionPrincipals) {
       this.cantidadParqueaderos = cantidadParqueaderos;
       this.informacionPrincipals = informacionPrincipals;
    }
   
    public Integer getIdParqueadero() {
        return this.idParqueadero;
    }
    
    public void setIdParqueadero(Integer idParqueadero) {
        this.idParqueadero = idParqueadero;
    }
    public String getCantidadParqueaderos() {
        return this.cantidadParqueaderos;
    }
    
    public void setCantidadParqueaderos(String cantidadParqueaderos) {
        this.cantidadParqueaderos = cantidadParqueaderos;
    }
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


