package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RangoPrecios generated by hbm2java
 */
public class RangoPrecios  implements java.io.Serializable {


     private Integer idRangoPrecios;
     private String cantidadPrecio;
     private Set<RangoPreciosAjustado> rangoPreciosAjustados = new HashSet<RangoPreciosAjustado>(0);

    public RangoPrecios() {
    }

	
    public RangoPrecios(String cantidadPrecio) {
        this.cantidadPrecio = cantidadPrecio;
    }
    public RangoPrecios(String cantidadPrecio, Set<RangoPreciosAjustado> rangoPreciosAjustados) {
       this.cantidadPrecio = cantidadPrecio;
       this.rangoPreciosAjustados = rangoPreciosAjustados;
    }
   
    public Integer getIdRangoPrecios() {
        return this.idRangoPrecios;
    }
    
    public void setIdRangoPrecios(Integer idRangoPrecios) {
        this.idRangoPrecios = idRangoPrecios;
    }
    public String getCantidadPrecio() {
        return this.cantidadPrecio;
    }
    
    public void setCantidadPrecio(String cantidadPrecio) {
        this.cantidadPrecio = cantidadPrecio;
    }
    public Set<RangoPreciosAjustado> getRangoPreciosAjustados() {
        return this.rangoPreciosAjustados;
    }
    
    public void setRangoPreciosAjustados(Set<RangoPreciosAjustado> rangoPreciosAjustados) {
        this.rangoPreciosAjustados = rangoPreciosAjustados;
    }




}


