package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RangoPreciosAjustado generated by hbm2java
 */
public class RangoPreciosAjustado  implements java.io.Serializable {


     private Integer idRangoPreciosAjustado;
     private RangoPrecios rangoPrecios;
     private TipoOperacion tipoOperacion;
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public RangoPreciosAjustado() {
    }

	
    public RangoPreciosAjustado(RangoPrecios rangoPrecios, TipoOperacion tipoOperacion) {
        this.rangoPrecios = rangoPrecios;
        this.tipoOperacion = tipoOperacion;
    }
    public RangoPreciosAjustado(RangoPrecios rangoPrecios, TipoOperacion tipoOperacion, Set<InformacionPrincipal> informacionPrincipals) {
       this.rangoPrecios = rangoPrecios;
       this.tipoOperacion = tipoOperacion;
       this.informacionPrincipals = informacionPrincipals;
    }
   
    public Integer getIdRangoPreciosAjustado() {
        return this.idRangoPreciosAjustado;
    }
    
    public void setIdRangoPreciosAjustado(Integer idRangoPreciosAjustado) {
        this.idRangoPreciosAjustado = idRangoPreciosAjustado;
    }
    public RangoPrecios getRangoPrecios() {
        return this.rangoPrecios;
    }
    
    public void setRangoPrecios(RangoPrecios rangoPrecios) {
        this.rangoPrecios = rangoPrecios;
    }
    public TipoOperacion getTipoOperacion() {
        return this.tipoOperacion;
    }
    
    public void setTipoOperacion(TipoOperacion tipoOperacion) {
        this.tipoOperacion = tipoOperacion;
    }
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


