package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Integer idRoles;
     private String nombreRol;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Roles() {
    }

	
    public Roles(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Roles(String nombreRol, Set<Usuario> usuarios) {
       this.nombreRol = nombreRol;
       this.usuarios = usuarios;
    }
   
    public Integer getIdRoles() {
        return this.idRoles;
    }
    
    public void setIdRoles(Integer idRoles) {
        this.idRoles = idRoles;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


