package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TiempoConstruido generated by hbm2java
 */
public class TiempoConstruido  implements java.io.Serializable {


     private Integer idTiempoConstruido;
     private String cantidadTiempoConstruido;
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public TiempoConstruido() {
    }

	
    public TiempoConstruido(String cantidadTiempoConstruido) {
        this.cantidadTiempoConstruido = cantidadTiempoConstruido;
    }
    public TiempoConstruido(String cantidadTiempoConstruido, Set<InformacionPrincipal> informacionPrincipals) {
       this.cantidadTiempoConstruido = cantidadTiempoConstruido;
       this.informacionPrincipals = informacionPrincipals;
    }
   
    public Integer getIdTiempoConstruido() {
        return this.idTiempoConstruido;
    }
    
    public void setIdTiempoConstruido(Integer idTiempoConstruido) {
        this.idTiempoConstruido = idTiempoConstruido;
    }
    public String getCantidadTiempoConstruido() {
        return this.cantidadTiempoConstruido;
    }
    
    public void setCantidadTiempoConstruido(String cantidadTiempoConstruido) {
        this.cantidadTiempoConstruido = cantidadTiempoConstruido;
    }
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


