package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPropiedad generated by hbm2java
 */
public class TipoPropiedad  implements java.io.Serializable {


     private Integer idTipoPropiedad;
     private String nombreTipoPropiedad;
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public TipoPropiedad() {
    }

	
    public TipoPropiedad(String nombreTipoPropiedad) {
        this.nombreTipoPropiedad = nombreTipoPropiedad;
    }
    public TipoPropiedad(String nombreTipoPropiedad, Set<InformacionPrincipal> informacionPrincipals) {
       this.nombreTipoPropiedad = nombreTipoPropiedad;
       this.informacionPrincipals = informacionPrincipals;
    }
   
    public Integer getIdTipoPropiedad() {
        return this.idTipoPropiedad;
    }
    
    public void setIdTipoPropiedad(Integer idTipoPropiedad) {
        this.idTipoPropiedad = idTipoPropiedad;
    }
    public String getNombreTipoPropiedad() {
        return this.nombreTipoPropiedad;
    }
    
    public void setNombreTipoPropiedad(String nombreTipoPropiedad) {
        this.nombreTipoPropiedad = nombreTipoPropiedad;
    }
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


