package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoInmueble generated by hbm2java
 */
public class TipoInmueble  implements java.io.Serializable {


     private Integer idTipoInmueble;
     private String nombreTipoInmueble;
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public TipoInmueble() {
    }

	
    public TipoInmueble(String nombreTipoInmueble) {
        this.nombreTipoInmueble = nombreTipoInmueble;
    }
    public TipoInmueble(String nombreTipoInmueble, Set<InformacionPrincipal> informacionPrincipals) {
       this.nombreTipoInmueble = nombreTipoInmueble;
       this.informacionPrincipals = informacionPrincipals;
    }
   
    public Integer getIdTipoInmueble() {
        return this.idTipoInmueble;
    }
    
    public void setIdTipoInmueble(Integer idTipoInmueble) {
        this.idTipoInmueble = idTipoInmueble;
    }
    public String getNombreTipoInmueble() {
        return this.nombreTipoInmueble;
    }
    
    public void setNombreTipoInmueble(String nombreTipoInmueble) {
        this.nombreTipoInmueble = nombreTipoInmueble;
    }
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


