package com.inmobiliaria.model;
// Generated 4/03/2015 09:08:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoOperacion generated by hbm2java
 */
@Entity
@Table(name="tipo_operacion"
    ,catalog="inmobiliaria"
)
public class TipoOperacion  implements java.io.Serializable {


     private int idTipoOperacion;
     private String nombreTipoOperacion;
     private Set rangoPreciosAjustados = new HashSet(0);
     private Set informacionPrincipals = new HashSet(0);

    public TipoOperacion() {
    }

	
    public TipoOperacion(int idTipoOperacion, String nombreTipoOperacion) {
        this.idTipoOperacion = idTipoOperacion;
        this.nombreTipoOperacion = nombreTipoOperacion;
    }
    public TipoOperacion(int idTipoOperacion, String nombreTipoOperacion, Set rangoPreciosAjustados, Set informacionPrincipals) {
       this.idTipoOperacion = idTipoOperacion;
       this.nombreTipoOperacion = nombreTipoOperacion;
       this.rangoPreciosAjustados = rangoPreciosAjustados;
       this.informacionPrincipals = informacionPrincipals;
    }
   
     @Id 

    
    @Column(name="id_tipo_operacion", unique=true, nullable=false)
    public int getIdTipoOperacion() {
        return this.idTipoOperacion;
    }
    
    public void setIdTipoOperacion(int idTipoOperacion) {
        this.idTipoOperacion = idTipoOperacion;
    }

    
    @Column(name="nombre_tipo_operacion", nullable=false, length=45)
    public String getNombreTipoOperacion() {
        return this.nombreTipoOperacion;
    }
    
    public void setNombreTipoOperacion(String nombreTipoOperacion) {
        this.nombreTipoOperacion = nombreTipoOperacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoOperacion")
    public Set getRangoPreciosAjustados() {
        return this.rangoPreciosAjustados;
    }
    
    public void setRangoPreciosAjustados(Set rangoPreciosAjustados) {
        this.rangoPreciosAjustados = rangoPreciosAjustados;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoOperacion")
    public Set getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


