package com.inmobiliaria.model;
// Generated 4/03/2015 09:08:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPropiedad generated by hbm2java
 */
@Entity
@Table(name="tipo_propiedad"
    ,catalog="inmobiliaria"
)
public class TipoPropiedad  implements java.io.Serializable {


     private Integer idTipoPropiedad;
     private String nombreTipoPropiedad;
     private Set informacionPrincipals = new HashSet(0);

    public TipoPropiedad() {
    }

	
    public TipoPropiedad(String nombreTipoPropiedad) {
        this.nombreTipoPropiedad = nombreTipoPropiedad;
    }
    public TipoPropiedad(String nombreTipoPropiedad, Set informacionPrincipals) {
       this.nombreTipoPropiedad = nombreTipoPropiedad;
       this.informacionPrincipals = informacionPrincipals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_propiedad", unique=true, nullable=false)
    public Integer getIdTipoPropiedad() {
        return this.idTipoPropiedad;
    }
    
    public void setIdTipoPropiedad(Integer idTipoPropiedad) {
        this.idTipoPropiedad = idTipoPropiedad;
    }

    
    @Column(name="nombre_tipo_propiedad", nullable=false, length=45)
    public String getNombreTipoPropiedad() {
        return this.nombreTipoPropiedad;
    }
    
    public void setNombreTipoPropiedad(String nombreTipoPropiedad) {
        this.nombreTipoPropiedad = nombreTipoPropiedad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoPropiedad")
    public Set getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


