package com.inmobiliaria.model;
// Generated 4/03/2015 12:23:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoOperacion generated by hbm2java
 */
public class TipoOperacion  implements java.io.Serializable {


     private int idTipoOperacion;
     private String nombreTipoOperacion;
     private Set<RangoPreciosAjustado> rangoPreciosAjustados = new HashSet<RangoPreciosAjustado>(0);
     private Set<InformacionPrincipal> informacionPrincipals = new HashSet<InformacionPrincipal>(0);

    public TipoOperacion() {
    }

	
    public TipoOperacion(int idTipoOperacion, String nombreTipoOperacion) {
        this.idTipoOperacion = idTipoOperacion;
        this.nombreTipoOperacion = nombreTipoOperacion;
    }
    public TipoOperacion(int idTipoOperacion, String nombreTipoOperacion, Set<RangoPreciosAjustado> rangoPreciosAjustados, Set<InformacionPrincipal> informacionPrincipals) {
       this.idTipoOperacion = idTipoOperacion;
       this.nombreTipoOperacion = nombreTipoOperacion;
       this.rangoPreciosAjustados = rangoPreciosAjustados;
       this.informacionPrincipals = informacionPrincipals;
    }
   
    public int getIdTipoOperacion() {
        return this.idTipoOperacion;
    }
    
    public void setIdTipoOperacion(int idTipoOperacion) {
        this.idTipoOperacion = idTipoOperacion;
    }
    public String getNombreTipoOperacion() {
        return this.nombreTipoOperacion;
    }
    
    public void setNombreTipoOperacion(String nombreTipoOperacion) {
        this.nombreTipoOperacion = nombreTipoOperacion;
    }
    public Set<RangoPreciosAjustado> getRangoPreciosAjustados() {
        return this.rangoPreciosAjustados;
    }
    
    public void setRangoPreciosAjustados(Set<RangoPreciosAjustado> rangoPreciosAjustados) {
        this.rangoPreciosAjustados = rangoPreciosAjustados;
    }
    public Set<InformacionPrincipal> getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set<InformacionPrincipal> informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


