package com.inmobiliaria.model;
// Generated 4/03/2015 09:08:20 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Zona generated by hbm2java
 */
@Entity
@Table(name="zona"
    ,catalog="inmobiliaria"
)
public class Zona  implements java.io.Serializable {


     private Integer idZona;
     private String nombreZona;
     private Set informacionPrincipals = new HashSet(0);

    public Zona() {
    }

	
    public Zona(String nombreZona) {
        this.nombreZona = nombreZona;
    }
    public Zona(String nombreZona, Set informacionPrincipals) {
       this.nombreZona = nombreZona;
       this.informacionPrincipals = informacionPrincipals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_zona", unique=true, nullable=false)
    public Integer getIdZona() {
        return this.idZona;
    }
    
    public void setIdZona(Integer idZona) {
        this.idZona = idZona;
    }

    
    @Column(name="nombre_zona", nullable=false, length=45)
    public String getNombreZona() {
        return this.nombreZona;
    }
    
    public void setNombreZona(String nombreZona) {
        this.nombreZona = nombreZona;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="zona")
    public Set getInformacionPrincipals() {
        return this.informacionPrincipals;
    }
    
    public void setInformacionPrincipals(Set informacionPrincipals) {
        this.informacionPrincipals = informacionPrincipals;
    }




}


